services:
  app:
    image: python:3.12-slim
    working_dir: /app
    volumes:
    - .:/app
    command: python main.py
    environment:
    - PYTHONUNBUFFERED=1
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
  web:
    image: python:3.12-slim
    working_dir: /app
    volumes:
    - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000
    environment:
    - PYTHONUNBUFFERED=1
    - DJANGO_SETTINGS_MODULE=project.settings
volumes:
  pgdata: null
