// docker-bake.hcl - Generated by Docker Compose YAML Generator
// Run with: docker buildx bake

group "default" {
  targets = ["development"]
}

group "production" {
  targets = ["app-production", "web-production"]
}

group "development" {
  targets = ["app-development", "web-development"]
}

// Default variables
variable "TAG" {
  default = "latest"
}

variable "REGISTRY" {
  default = ""
}

target "app-development" {
  context = "."
  dockerfile = "app.Dockerfile"
  tags = ["${REGISTRY}app:development"]
  cache-from = ["type=registry,ref=${REGISTRY}app:buildcache"]
  cache-to = ["type=inline"]
  target = "development"
  args = {
    BUILDKIT_INLINE_CACHE = "1"
  }
}

target "app-production" {
  context = "."
  dockerfile = "app.Dockerfile"
  tags = ["${REGISTRY}app:${TAG}"]
  cache-from = ["type=registry,ref=${REGISTRY}app:buildcache"]
  platforms = ["linux/amd64", "linux/arm64"]
  target = "production"
  args = {
    BUILDKIT_INLINE_CACHE = "1"
  }
}

target "web-development" {
  context = "."
  dockerfile = "web.Dockerfile"
  tags = ["${REGISTRY}web:development"]
  cache-from = ["type=registry,ref=${REGISTRY}web:buildcache"]
  cache-to = ["type=inline"]
  target = "development"
  args = {
    BUILDKIT_INLINE_CACHE = "1"
  }
}

target "web-production" {
  context = "."
  dockerfile = "web.Dockerfile"
  tags = ["${REGISTRY}web:${TAG}"]
  cache-from = ["type=registry,ref=${REGISTRY}web:buildcache"]
  platforms = ["linux/amd64", "linux/arm64"]
  target = "production"
  args = {
    BUILDKIT_INLINE_CACHE = "1"
  }
}
